### ISSUE TITLE
Create singularity container to run Bruker Prairie View software

### ISSUE THREAD

**Issue by chrisroat** [deisseroth-lab/two-photon#2]
@vsoch, croat-singularity branch has the Dockerfile + instructions I've gotten written so far.  The process worked once, but it turns out it was likely due to my external ~/.wine directory being mounted.  Things stopped working when I ran the container after my ~/.wine directory was reset.  The leads me to believe that I need to avoid mounting my home directory, and setup an container-internal ~/.wine directory -- but I don't know what is needed.

Dockerfile:
https://github.com/deisseroth-lab/two-photon/blob/croat-singularity/Dockerfile

README with instructions 
https://github.com/deisseroth-lab/two-photon/blob/croat-singularity/README.md

This has been heavily influenced by dissecting a repo by @scotthardy, and it's docker-wine scripts
https://github.com/scottyhardy/docker-wine
https://github.com/scottyhardy/docker-wine/blob/master/docker-wine

**Comment by vsoch** [comment]
okay, I have the .exe that I found running in the Singularity container - 
![image](https://user-images.githubusercontent.com/814322/91666620-86d34c80-eabb-11ea-85b8-81b7878d8d71.png)

Do you have some dummy data I can test for the python script?

**Comment by tbenst** [comment]
@vsoch great to have your help on this!

Here's a sample data folder: https://drive.google.com/drive/folders/12niUpCXgOSX3sXFEdT-KhYjXCWVdhrE6?usp=sharing

The expected output is a single .tiff file like so: https://drive.google.com/file/d/1Vot4tO8BWdCDitALSexkibSO2sjPvHI-/view?usp=sharing (note that folder was named `overview-23` on my computer rather than `bruker-example`, hence filename)

Indeed, we believe the raw data is 203MB while the tif of same data is 526kB, (proprietary data formats :man_shrugging:)

**Comment by vsoch** [comment]
Thank you! I'll give that a shot.

**Comment by tbenst** [comment]
if you get an error on conversion, you likely need to do `winetricks -q vcrun2015`

**Comment by vsoch** [comment]
Ha! Yes I did get that error, and realized I needed to install it.

**Comment by vsoch** [comment]
Sorry to be dense - stupid question - why is the image entirely black?

**Comment by vsoch** [comment]
Seems to be the right size!
```
$ ls -l overview-23/overview-023_Cycle00001_Ch3_000001.ome.tif 
-rw-r--r-- 1 vanessa vanessa 526404 Aug 30 13:32 overview-23/overview-023_Cycle00001_Ch3_000001.ome.tif
```
I'll open up a PR with instructions to reproduce this!

**Comment by vsoch** [comment]
It's so weird that the file lists and other supporting files just go away after you run it. I guess I'll chock this up to weird Windows logic :P

**Comment by tbenst** [comment]
> Sorry to be dense - stupid question - why is the image entirely black?
Not dumb at all! It's just *very* dim. If you open with [ImageJ/Fiji](https://imagej.net/Fiji), you will see a very crummy picture of a zebrafish brain, symmetrical on x-axis...sorry I didn't choose a better photo ;)
